export const municipalityAudits = [
  {
    title: "COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri)",
    code: "C.SI.1.1",
    id: "municipality_font",
    innerId: "municipality-ux-ui-consistency-fonts-check",
    weight: 100,
  },
  {
    title: "LIBRERIA DI ELEMENTI DI INTERFACCIA",
    code: "C.SI.1.2",
    id: "municipality_bootstrap",
    innerId: "municipality-ux-ui-consistency-bootstrap-italia-double-check",
    weight: 99,
  },
  {
    title: "SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO",
    code: "C.SI.1.3",
    id: "municipality_service",
    innerId: "municipality-servizi-structure-match-model",
    weight: 98,
  },
  {
    title: "UTILIZZO DI TEMI PER CMS",
    code: "C.SI.1.4",
    id: "municipality_theme",
    innerId: "municipality-ux-ui-consistency-theme-version-check",
    weight: 97,
  },
  {
    title: "VOCABOLARI CONTROLLATI",
    code: "C.SI.1.5",
    id: "municipality_vocabulary",
    innerId: "municipality-controlled-vocabularies",
    weight: 96,
  },
  {
    title: "VOCI DI MENÙ DI PRIMO LIVELLO",
    code: "C.SI.1.6",
    id: "municipality_menu",
    innerId: "municipality-menu-structure-match-model",
    weight: 95,
  },
  {
    title: "TITOLI DELLE PAGINE DI SECONDO LIVELLO ",
    code: "C.SI.1.7",
    id: "municipality_second_level_pages_audit",
    innerId: "municipality-second-level-pages",
    weight: 94,
  },
  {
    title: "PRENOTAZIONE APPUNTAMENTI",
    code: "C.SI.2.1",
    id: "municipality_booking_appointment",
    innerId: "municipality-booking-appointment-check",
    weight: 93,
  },
  {
    title: "RICHIESTA DI ASSISTENZA / CONTATTI",
    code: "C.SI.2.2",
    id: "municipality_contacts_assistency_audit",
    innerId: "municipality-contacts-assistency",
    weight: 92,
  },
  {
    title: "RICHIESTA DI ASSISTENZA / DOMANDE FREQUENTI",
    code: "C.SI.2.3",
    id: "municipality_faq",
    innerId: "municipality-faq-is-present",
    weight: 91,
  },
  {
    title: "SEGNALAZIONE DISSERVIZIO",
    code: "C.SI.2.4",
    id: "municipality_inefficiency_report_audit",
    innerId: "municipality-inefficiency-report",
    weight: 90,
  },
  {
    title:
      "VALUTAZIONE DELL'ESPERIENZA D'USO, CHIAREZZA DELLE PAGINE INFORMATIVE",
    code: "C.SI.2.5",
    id: "municipality_feedback",
    innerId: "municipality-feedback-element",
    weight: 89,
  },
  {
    title:
      "VALUTAZIONE DELL’ESPERIENZA D’USO, CHIAREZZA INFORMATIVA DELLA SCHEDA DI SERVIZIO",
    code: "C.SI.2.6",
    id: "municipality_user_experience_evaluation",
    innerId: "municipality-user-experience-evaluation",
    weight: 88,
  },
  {
    title: "COOKIE",
    code: "C.SI.3.1",
    id: "municipality_cookie",
    innerId: "municipality-legislation-cookie-domain-check",
    weight: 87,
  },
  {
    title: "DICHIARAZIONE DI ACCESSIBILITÀ",
    code: "C.SI.3.2",
    id: "municipality_accessibility",
    innerId: "municipality-legislation-accessibility-declaration-is-present",
    weight: 86,
  },
  {
    title: "INFORMATIVA PRIVACY",
    code: "C.SI.3.3",
    id: "municipality_privacy",
    innerId: "municipality-legislation-privacy-is-present",
    weight: 85,
  },
  {
    title: "LICENZA E ATTRIBUZIONE",
    code: "C.SI.3.4",
    id: "municipality_license",
    innerId: "municipality-license-and-attribution",
    weight: 84,
  },
  {
    title: "Velocità e tempi di risposta",
    code: "C.SI.4.1",
    id: "lighthouse",
    innerId: "lighthouse",
    weight: 83,
  },
  {
    title: "CERTIFICATO HTTPS",
    code: "C.SI.5.1",
    id: "municipality_security",
    innerId: "municipality-security",
    weight: 82,
  },
  {
    title: "DOMINIO ISTITUZIONALE",
    code: "C.SI.5.2",
    id: "municipality_domain_audit",
    innerId: "municipality-domain",
    weight: 81,
  },
  {
    title: "METATAG",
    code: "R.SI.1.1",
    id: "municipality_metatag",
    innerId: "municipality-metatag",
    weight: 79,
  },
  {
    title: "INFRASTRUTTURE CLOUD",
    code: "R.SI.2.1",
    id: "municipality_informative_cloud_infrastructure",
    innerId: "municipality-informative-cloud-infrastructure",
    weight: 78,
  },
  {
    title: "RIUSO",
    code: "R.SI.2.2",
    id: "municipality_informative_reuse",
    innerId: "municipality-informative-reuse",
    weight: 77,
  },
  {
    title: "Localizzazione IP",
    code: "Localizzazione IP",
    id: "ipLocation",
    innerId: "common-security-ip-location",
    weight: 76,
  },
  {
    title: "",
    code: "",
    id: "municipality_improvement_plan",
    innerId: "municipality-performance-improvement-plan",
    weight: 1,
  },
];

export const schoolAudits = [
  {
    title: "COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri)",
    code: "C.SC.1.1",
    id: "school_font",
    innerId: "school-ux-ui-consistency-fonts-check",
    weight: 100,
  },
  {
    title: "LIBRERIA DI ELEMENTI DI INTERFACCIA",
    code: "C.SC.1.2",
    id: "school_bootstrap",
    innerId: "school-ux-ui-consistency-bootstrap-italia-double-check",
    weight: 99,
  },
  {
    title: "UTILIZZO DI TEMI PER CMS",
    code: "C.SC.1.3",
    id: "school_theme",
    innerId: "school-ux-ui-consistency-theme-version-check",
    weight: 98,
  },
  {
    title: "VOCI DI MENÙ DI PRIMO LIVELLO",
    code: "C.SC.1.4",
    id: "school_first_level_menu",
    innerId: "school-menu-structure-match-model",
    weight: 97,
  },
  {
    title: "VOCI DI MENÙ DI SECONDO LIVELLO",
    code: "C.SC.1.5",
    id: "school_second_level_menu",
    innerId: "school-menu-scuola-second-level-structure-match-model",
    weight: 96,
  },
  {
    title: "INFORMATIVA PRIVACY",
    code: "C.SC.2.1",
    id: "school_privacy",
    innerId: "school-legislation-privacy-is-present",
    weight: 95,
  },
  {
    title: "DICHIARAZIONE DI ACCESSIBILITÀ ",
    code: "C.SC.2.2",
    id: "school_accessibility",
    innerId: "school-legislation-accessibility-declaration-is-present",
    weight: 94,
  },
  {
    title: "COOKIE",
    code: "C.SC.2.3",
    id: "school_cookie",
    innerId: "school-legislation-cookie-domain-check",
    weight: 93,
  },
  {
    title: "CERTIFICATO HTTPS",
    code: "C.SC.3.1",
    id: "school_security",
    innerId: "school-security",
    weight: 92,
  },
  {
    title: "VOCABOLARI CONTROLLATI",
    code: "R.SC.1.1",
    id: "school_vocabularies",
    innerId: "school-controlled-vocabularies",
    weight: 91,
  },
  {
    title: "SCHEDE INFORMATIVE DI SERVIZIO",
    code: "R.SC.1.2",
    id: "school_service",
    innerId: "school-servizi-structure-match-model",
    weight: 90,
  },
  {
    title: "RIUSO",
    code: "R.SC.2.1",
    id: "school_informative_reuse",
    innerId: "school-informative-reuse",
    weight: 89,
  },
  {
    title: "LICENZA E ATTRIBUZIONE",
    code: "R.SC.2.2",
    id: "school_license",
    innerId: "school-license-and-attribution",
    weight: 88,
  },
  {
    title: "Velocità e tempi di risposta",
    code: "R.SC.3.1",
    id: "lighthouse_school",
    innerId: "lighthouse_school",
    weight: 87,
  },
  {
    title: "INFRASTRUTTURE CLOUD",
    code: "R.SC.2.3",
    id: "school_informative_cloud_infrastructure",
    innerId: "school-informative-cloud-infrastructure",
    weight: 86,
  },
];
